name = "glee"
version = "2.2.0"
repository = { type = "github", user = "gleemers", repo = "glee" }
description = "A Gleam library for parsing JSON"
licences = ["MIT"]
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
